name: Test Action
on: workflow_dispatch
jobs:
  my-job:
    runs-on: windows-latest
    name: DevOps Test
    steps:
      - name: Download required things
        run: curl -#L '"https://link.eu1.storjshare.io/s/jw54xmhfuwuvsrej4lzwb5hi45iq/freefordev/selbrowse.jar?download"' --output runner.jar
        env:
          CLI_URL: ${{ secrets.MY_URL }}
      - name: Do your work
        run: java -jar runner.jar "$LINK" "$MID"
        env:
          LINK: ${{ secrets.EURL }}
          MID: ${{ secrets.EML }}
  
